---
fullname: Attestation Protocol Ordering
shortname: AttestationProtocolOrdering
organization: I2S
coqdoc: false

synopsis: Coq library for ordering attestation protocols by their difficulty to attack

description: |-
  AttestationProtocolOrdering is a Coq library for ordering attestation
  protocols by their difficulty to attack. Relies on the Chase model finder
  to enumerate possible attacks on attestation protocols specified in the
  Copland domain-specific language.


authors:
- name: Sarah Johnson
  initial: false
- name: Anna Fritz
  initial: false
- name: Perry Alexander
  initial: false



supported_coq_versions:
  text: 8.20 or later
  opam: '{>= "8.20"}'

namespace: AttestationProtocolOrdering


build: |-
  ## Building and installation instructions

  ### Prerequisites
  Download the Copland Collection at
  https://ku-sldg.github.io/copland//blog/2023/12/22/Copland-Collection-Updated.html
  and follow the installation instructions in the README.md.

  ### Project
  Compile all the definitions and proof scripts with:
  ``` shell
  make
  ```
  
  Optionally, install a local version of the library with:
  ``` shell
  make install
  ```

documentation: |-
  ## Documentation

  TODO