---
fullname: Attestation Protocol Ordering
shortname: AttestationProtocolOrdering
organization: I2S
coqdoc: false

synopsis: Coq library for ordering attestation protocols by their difficulty to attack

description: |-
  AttestationProtocolOrdering is a Coq library for ordering attestation
  protocols by their difficulty to attack. Relies on the Chase model finder
  to enumerate possible attacks on attestation protocols specified in the
  Copland domain-specific language.


authors:
- name: Sarah Johnson
  initial: false
- name: Anna Fritz
  initial: false
- name: Perry Alexander
  initial: false


maintainers:
- name: Sarah Johnson
  nickname: Sarah-Scott

opam-file-maintainer: sarahjohnson@ku.edu

supported_coq_versions:
  text: 8.20 or later
  opam: '{>= "8.20"}'

namespace: AttestationProtocolOrdering


build: |-
  ## Building and installation instructions
  Get Chase Copland first
  Then something

documentation: |-
  ## Documentation

  Attestation Protocol Ordering is cool.
  Here are file descriptions